language: php
php:
  - 5.3.3
  - 5.4
  - 5.5
branches:
  only:
    - /^7.x/
env:
  - FEDORA_VERSION="3.5"
  - FEDORA_VERSION="3.6.2"
  - FEDORA_VERSION="3.7.0"
before_install:
  - cd $HOME
  - git clone -b 7.x git://github.com/Islandora/islandora.git
  - git clone -b 7.x git://github.com/Islandora/islandora_solution_pack_collection.git
  - git clone -b 7.x git://github.com/discoverygarden/islandora_binary_object.git
  - git clone -b 7.x git://github.com/Islandora/islandora_importer.git
  - git clone -b 7.x git://github.com/Islandora/islandora_batch.git
  - export ISLANDORA_DIR=$HOME/islandora
  - $HOME/islandora/tests/scripts/travis_setup.sh
  - $TRAVIS_BUILD_DIR/tests/scripts/travis_setup.sh
  - cd $HOME/drupal-*
  - mv ../indigo-python-1.1.12-linux sites/all/libraries/indigo-python
  - ln -s $TRAVIS_BUILD_DIR sites/all/modules/islandora_solution_pack_chemistry
  - ln -s $HOME/islandora_solution_pack_collection sites/all/modules/islandora_solution_pack_collection
  - ln -s $HOME/islandora_binary_object sites/all/modules/islandora_binary_object
  - ln -s $HOME/islandora_importer sites/all/modules/islandora_importer
  - ln -s $HOME/islandora_batch sites/all/modules/islandora_batch
  - drush -y -u 1 dl libraries && drush -y -u 1 en libraries
  - drush en --user=1 --yes islandora_basic_collection islandora_chemistry
script:
  - ant -buildfile sites/all/modules/islandora_solution_pack_chemistry/build.xml lint
  - $ISLANDORA_DIR/tests/scripts/line_endings.sh sites/all/modules/islandora_solution_pack_chemistry
  - drush coder-review --reviews=production,security,style,i18n,potx,sniffer islandora_chemistry
  - phpcpd --names *.module,*.inc,*.test sites/all/modules/islandora_solution_pack_chemistry
  - phpunit sites/all/modules/islandora_solution_pack_chemistry/tests/openbabel.test.php
  - phpunit sites/all/modules/islandora_solution_pack_chemistry/tests/checkmol.test.php
  - drush test-run --uri=http://localhost:8081 "Islandora Chemistry"
after_failure:
  - $ISLANDORA_DIR/tests/scripts/travis_after_failure.sh
